export interface StudentPodaci {
    ime;
    prezime;
    spol;
    datumRodenja;
    oib;
    jmbg;
    jmbag;
    brojMobitela;
    grad;
    opcina;
    drzava;
    nacionalnost;
    imeOca;
    imeMajke;
    nazivSkole;
    godinaZavrsetkaSkole;
    strukovnoPodrucje;
    programIzobrazbe;
    razinaPravaNaPrehranu;
    datumPravaOd;
    datumPravaDo;
    redniBrojMaticnaKnjizica;
    lokalniMaticniBroj;
    statusElektricnogIdentiteta;
    AAIoznaka;
    AAIUID;
    datumUpisa;
    datumIspisa;
    datumPodizanjaDokumenta;
    razlogPrestankaStudentskihPrava;
    studentIzDijaspore;
    brojKopijaIndeksa;
    aktivanEmail;

}
